[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "radiate"
description = "A fast and flexible evolution engine for implementing artificial evolution and genetic programming techniques."
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
]
dynamic = ["version"]

[project.optional-dependencies]
numpy = ["numpy>=1.20.0"]
numba = ["numba>=0.61.2"]

all = [
    "radiate[numpy,numba]",
]

[project.test-dependencies]
numpy = ["numpy>=1.20.0"]
numba = ["numba>=0.61.2"]

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.ruff]
line-length = 88
fix = true

