# This file is auto-generated by setuptools_scm
# Do not edit manually

# __version__ = "0.0.11"
# __version_tuple__ = (0, 0, 11)

from radiate.radiate import py_version

__version__ = py_version()
__version_tuple__ = tuple(map(int, __version__.split(".")))
