class PyEngineControl:
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...
    def step(self) -> None: ...

class PyGeneration:
    def index(self) -> int: ...
    def score(self) -> float: ...

class PyEngine:
    def __iter__(self) -> "PyEngine": ...
    def __next__(self) -> "PyGeneration": ...
    def control(self) -> "PyEngineControl": ...
