[package]
name = "regression-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
radiate = { workspace = true, features = ["gp", "serde", "pgm"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0" }