[package]
name = "radiate-metrics"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
radiate-error = { workspace = true }
radiate-utils = { workspace = true }

[dev-dependencies]
radiate-test = { workspace = true }

[features]
default = []
serde = ["dep:serde", "radiate-utils/serde"]
