[env]
RADIATE_PYTHON_VERSION = "3.12"
UV_PROJECT_ENVIRONMENT = ".venv"


[alias]
ex-hello-world    = "run --manifest-path examples/hello-world/Cargo.toml"
ex-knapsack       = "run --manifest-path examples/knapsack/Cargo.toml"
ex-min-sum        = "run --manifest-path examples/min-sum/Cargo.toml"
ex-nqueens        = "run --manifest-path examples/nqueens/Cargo.toml"
ex-rastrigin      = "run --manifest-path examples/rastrigin/Cargo.toml"
ex-rosenbrock     = "run --manifest-path examples/rosenbrock/Cargo.toml"
ex-simple-nn      = "run --manifest-path examples/simple-nn/Cargo.toml"
ex-TSP            = "run --manifest-path examples/TSP/Cargo.toml"
ex-DTLZ           = "run --manifest-path examples/DTLZ/Cargo.toml"

# graphs/*
ex-graphs-iris         = "run --manifest-path examples/graphs/iris-graph/Cargo.toml"
ex-graphs-regression   = "run --manifest-path examples/graphs/regression-graph/Cargo.toml"
ex-graphs-simple-mem   = "run --manifest-path examples/graphs/simple-memory-graph/Cargo.toml"
ex-graphs-xor          = "run --manifest-path examples/graphs/xor-graph/Cargo.toml"

# trees/*
ex-trees-iris          = "run --manifest-path examples/trees/iris-tree/Cargo.toml"
ex-trees-regression    = "run --manifest-path examples/trees/regression-tree/Cargo.toml"

# image-evo (top-level example with multiple files)
ex-image-evo      = "run --manifest-path examples/image-evo/Cargo.toml"

py = ["make", "--makefile", ".cargo/Makefile.toml", "cargo-py"]
ex = ["make", "--makefile", ".cargo/Makefile.toml", "example-run", "--"]