name: py-unit-tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Create virtual environment
        run: |
          python -m venv .venv
          echo "$GITHUB_WORKSPACE/py-radiate/.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/py-radiate/.venv" >> $GITHUB_ENV

      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --features gil --out dist
          working-directory: py-radiate

      - name: Install wheel and test dependencies
        run: |
          pip install radiate --find-links py-radiate/dist --force-reinstall
          pip install pytest
          pip install -r py-radiate/requirements-dev.txt

      - name: Run tests
        working-directory: py-radiate
        run: |
          pytest tests --import-mode=importlib
          