name: py-unit-tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist
          working-directory: py-radiate

      # - name: Install wheel and dependencies
      #   run: |
      #     python3 -m venv .venv
      #     source .venv/bin/activate
      #     pip install radiate --find-links py-radiate/dist --force-reinstall
      #     pip install pytest

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest