name: py-unit-tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Create virtual environment
        run: |
          python -m venv .venv
          echo "$GITHUB_WORKSPACE/py-radiate/.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/py-radiate/.venv" >> $GITHUB_ENV

      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist -m py-radiate/Cargo.toml

      - name: Install Python dependencies
        run: |
          pip install uv
          uv pip install --compile-bytecode -r py-radiate/requirements-dev.txt

      - name: Set up Rust
        run: rustup show

      - name: Run tests
        # working-directory: py-radiate
        run: |
          uv run py-radiate/pytest tests --import-mode=importlib 
          