name: py-unit-tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run Python tests
        run: make test-py

      # - name: Create virtual environment
      #   working-directory: py-radiate
      #   run: |
      #     python -m venv .venv
      #     echo "$GITHUB_WORKSPACE/py-radiate/.venv/bin" >> $GITHUB_PATH
      #     echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/py-radiate/.venv" >> $GITHUB_ENV

      # - name: Install Python dependencies
      #   run: |
      #     $GITHUB_WORKSPACE/py-radiate/.venv/bin/pip install -r py-radiate/requirements-dev.txt

      # - name: Build and install py-radiate
      #   working-directory: py-radiate
      #   run: |
      #     $GITHUB_WORKSPACE/py-radiate/.venv/bin/pip install maturin
      #     $GITHUB_WORKSPACE/py-radiate/.venv/bin/maturin develop 

      # - name: Run tests
      #   working-directory: py-radiate
      #   run: |
      #     $GITHUB_WORKSPACE/py-radiate/.venv/bin/python -m pytest tests --import-mode=importlib 
          